import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { ClerkProvider } from "@clerk/nextjs";
import Nav from "./components/Nav";
import { auth } from "@clerk/nextjs/server";
import { InvitationListener } from "./components/InvitationListener";
import { Toaster } from "@/components/ui/toaster";
import { getUserFromDatabase } from "@/services/userService";
import { redirect } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic={true}>
      <StoreProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Nav />
            {children}

            <Toaster />
          </body>
        </html>
      </StoreProvider>
    </ClerkProvider>
  );
}
